### ISSUE TITLE
ESP32 and ESP8266 compile patch

### ISSUE THREAD

**Issue by BJDev95** [adafruit/Adafruit-SSD1331-OLED-Driver-Library-for-Arduino#11]
To compile this library the following patch is required to Adafruit_SSD1331.h

```
29,31d28
< #elif defined(ESP32) || defined(ESP8266)
< typedef volatile uint32_t PortReg;
< typedef uint32_t PortMask;
```

Please add this!

**Comment by ladyada** [comment]
hiya i think we fixed this in the "spitft" branch - can you try that and let me know?
