### ISSUE TITLE
You set precharge A, B and A again (instead of C)

### ISSUE THREAD

**Issue by urjaman** [adafruit/Adafruit-SSD1331-OLED-Driver-Library-for-Arduino#13]
The comment on this line would indicate precharge C, but the command is A:
https://github.com/adafruit/Adafruit-SSD1331-OLED-Driver-Library-for-Arduino/blob/a5d794c25172783fd36b86f3d2ed5df531e29e48/Adafruit_SSD1331.cpp#L346

**Comment by adavidzh** [comment]
This is addressed in #12.
